name: OpenMRS Main

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies and run tests
        env:
          YARN_ENABLE_HARDENED_MODE: 0
        run: yarn install
      - name: Run tests
        run: yarn test
